name: zmarthubsrv # you probably want to 'snapcraft register <name>'
version: '0.2'
summary: ZmartHUB server manager
description: |
  Zmartify's server manager for ZmartHUB

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots



slots:
  dbus-bluez:
    interface: dbus
    bus: system
    name: org.bluez
  dbus-freedesktop:
    interface: dbus
    bus: system
    name: org.freedesktop.DBus

plugs:
  client:
    interface: bluetooth-control

parts:
  jre:
    plugin: zulu-jre
        # zulu supported architectures(armhf, arm64,  amd64) are already handled by plugin itself
        # define here overide for pluging's defaults, or to add additional architectures
        # example overide:
        # zulu:
        #     amd64: https://www.azul.com/downloads/zulu/zdk-8-ga-linux_x64.tar.gz

  zmarthubsrv:
    plugin: maven
    source: git://github.com/zmartify/zmarthubsrv
    stage-packages:
      - libbluetooth-dev

apps:
  zmarthubsrv:
    command: java -jar $SNAP/jar/zmarthubsrv.jar
    daemon: simple
    plugs: [home, bluetooth-control, network, network-bind, network-manager, client]
  

